### ISSUE TITLE
Separate Standard vs Non-standard Headers

### ISSUE THREAD

**Issue by jordantrizz** [hubertnguyen/ismysitecached_public#1]
If possible common and standard HTTP headers should be placed in a single container while non-standard can be placed in another container. Additionally, provide an option to tag or categorize the non-standard headers to allow visitors to flag non-standard headers with notes so you get feedback on headers and can update the detection easily.

**Comment by hubertnguyen** [comment]
Hi Jordan, it's an interesting idea. Perhaps we could define what the standard headers are. What about:

0
accept-ranges
connection
content-length
content-type
date
server
vary

**Comment by jordantrizz** [comment]
100% that's a start!

**Comment by hubertnguyen** [comment]
I'll take a look. Another option is to add a toggle to show/hide the standard ones. And perhaps the setting could be saved in the browser.

**Comment by jordantrizz** [comment]
Please implement this :)

**Comment by hubertnguyen** [comment]
Rounding up the API then will take look

**Comment by hubertnguyen** [comment]
I just pushed an updated online test with the first version of this feature and There's a toggle button to show the hidden headers. By default, the following HTTP headers  will be hidden (via CSS)
- 'accept-ranges', 'connection', 'content-length', 'content-type', 'server'

Also, HTTP Headers that contain the following text will also be considered standard, and hidden:
- 'link', 'date'

I left vary because traffic split can sometimes explain caching problems, but perhaps "standard  vary" stuff could be detected and removed as well. 

<img src="https://i.imgur.com/3t6Amfs.png">

**Comment by jordantrizz** [comment]
Looks great!

**Comment by hubertnguyen** [comment]
Thanks @jordantrizz . I've added 7-8 more exclusions and that'll be in the next udpate later today. I'll close this one for now.
